# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Tests with Maven
      run: mvn clean test site

    - name: Artefacts Upload
      uses: actions/upload-artifact@v3
      with:
        name: Tests report
        path: target/site

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Artefacts Upload
        uses: actions/upload-artifact@v3
        with:
          name: JAR package
          path: target/out

  notification:
    needs: test
    runs-on: ubuntu-latest
    env:
      EMAIL_DEST: joaohsdelfino@gmail.com
    steps:
      - uses: actions/checkout@v3
      - name: Send notification using mail
        run: cd scripts/ && sh notify.sh